name: kls_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  youtube_explode_dart: ^2.3.10
  youtube_player_flutter: ^9.1.1
  just_audio: ^0.9.46
  just_audio_background: ^0.0.1-beta.15
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  youtube_scrape_api: ^0.1.0
  flutter_slidable: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  audio_video_progress_bar: ^2.0.3
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
